Gold list on Character Viewer
Orcpub/orcpub pull request #166
Opened 2019-04-27 10:13 UTC by marloso2

The Character Viewer shows the character's Money and Gems under a Treasure subheading in the Equipment tab

2019-04-27 20:14 UTC, datdamnzotz requested changes

2019-04-27 20:14 UTC, johnliss commented on src/cljs/orcpub/dnd/e5/views.cljs
> +                  [:tr.pointer
Let's take out the mouse cursor change to pointer, since there is nothing to click on....
Change `[:tr.pointer` to just `[:tr`

2019-04-27 20:14 UTC, johnliss commented on src/cljs/orcpub/dnd/e5/views.cljs
> +                  [:tr.pointer
Also take the pointer off the `(defn other-equipment-section-2 []` above.

2019-04-27 20:15 UTC, johnliss commented
Also now I am not too sure about the sorting.  Maybe we should leave it out, or recode it for ordering like the book does.
![image](https://user-images.githubusercontent.com/3913859/56854629-ebdec700-68f6-11e9-9878-fe896d652917.png)

2019-05-08 00:57 UTC, KingMob requested changes
There's a mismatch between the component fn params and the render fn params. `with-let` is probably your best solution

2019-05-08 00:57 UTC, KingMob commented on src/cljs/orcpub/dnd/e5/views.cljs
> +    (fn [id]
If all you're doing with a Form-2 component is creating ratoms before returning the rendering fn, you should prefer reagent's [`with-let`](https://cljdoc.org/d/reagent/reagent/0.9.0-SNAPSHOT/doc/tutorials/creating-reagent-components#appendix-b---with-let-macro) macro instead.

It's less error-prone for the reason seen here: there's a mismatch between the params passed into the component fn and the returned render fn 😄  (`id` is in the render fn, but not the top-level `treasure-section`)

2019-07-21 10:40 UTC, marloso2 commented
So that's the suggetsed improvements. Must say, I completely missed the `.pointer`. And thanks for the r/with-let, King. Either way, that leaves the question - Do we want alphabetical sorting, or no? I'm not sure yet how to do sorting to a custom order so someone else would have to do that once ths is pulled

2019-07-21 21:43 UTC, datdamnzotz commented
> So that's the suggetsed improvements. Must say, I completely missed the `.pointer`. And thanks for the r/with-let, King. Either way, that leaves the question - Do we want alphabetical sorting, or no? I'm not sure yet how to do sorting to a custom order so someone else would have to do that once this is pulled

I would vote for if we can do it like the book sorts it.

2019-07-23 02:13 UTC, marloso2 commented
> 
> > I'm not sure yet how to do sorting to a custom order
> 
> I would vote for if we can do it like the book sorts it.

Welp, as I said, I have absolutely no idea how to do that so somebody else would have to 😋

2019-07-23 15:13 UTC, codeGlaze commented
Wait, isn't treasure already sorted in a logical order?

2019-07-23 15:15 UTC, marloso2 commented
By default it's sorted in the order that it's added to your character. But we've also got the code for alphabetical sorting

2019-07-27 01:59 UTC, KingMob commented on src/cljs/orcpub/dnd/e5/views.cljs
> +    (fn [id]
Heh, if you're using `with-let`, you won't return a render function. It goes from a reagent Form-2 to a Form-1. And you'll need to add the missing `id` param to the main component fn.

Like:

```clojure
(defn treasure-section [id]
  (r/with-let [expanded-details (r/atom {})]
    (let [mobile? @(subscribe [:mobile?])
          treasure-cfgs @(subscribe [::char/treasure id])]
      ...
```

2019-07-27 02:13 UTC, KingMob commented
The treasure is stored in equipment.cljc in book order by default, but that doesn't help us sort a character's treasures. (Well, we could fake it by searching on strings and comparing indices, but that's slow and ugly.)

Instead, we should just make the order explicit, so it'll be available for sorting with [`sort-by`](https://clojuredocs.org/clojure.core/sort-by).

E.g.:

```clojure 
(def treasure
  [{:key :cp
    :name "Copper Pieces (CP)"}
   {:key :sp
    :name "Silver Pieces (SP)"}
   {:key :ep
    :name "Electrum Pieces (EP)"}
   {:key :gp
    :name "Gold Pieces (GP)"}
   ...
```

becomes

```clojure 
(def treasure
  [{:key :cp
    :name "Copper Pieces (CP)"
    :rank 1}
   {:key :sp
    :name "Silver Pieces (SP)"
    :rank 2}
   {:key :ep
    :name "Electrum Pieces (EP)"
    :rank 3}
   {:key :gp
    :name "Gold Pieces (GP)"
    :rank 4}
   ...
```

and then if we have a sequence of character treasures with the `:rank` field in them, we can do:

```clojure
(sort-by :rank some-character-treasure-vector)
```

I think that, or something similar, should work.

2019-07-27 02:31 UTC, marloso2 commented
Ahh, that's quite a good solution, actually. I'm working on something else right now but next time I get fed up with that I'll come back to this PR and add the ordering 😋

2019-07-27 19:47 UTC, KingMob commented
Another alternative is to place the character's treasure into a sorted map/set with `sorted-map-by` / `sorted-set-by`. Then, when you want to iterate over the map, they'll come out sorted.

2019-09-12 05:09 UTC, datdamnzotz commented
@marloso2 see #231 as well.

2019-09-12 16:20 UTC, datdamnzotz approved these changes

2019-09-12 18:56 UTC, datdamnzotz commented
I'm going to merge this to get the fixes into the branch.  I don't think sorting should hold this up.

2019-09-12 18:56 UTC, merged

2019-09-23 16:28 UTC, KingMob commented
Sorry @datdamnzotz, been real busy with life lately.

2019-09-23 17:41 UTC, codeGlaze commented
@KingMob we've all been pretty quiet. I assumed that was the case all around