Made email  SSL configurable.
Orcpub/orcpub pull request #205
Opened 2019-07-14 16:37 UTC by RubberRobot

2019-07-15 23:33 UTC, KingMob commented
@RubberRobot Thanks for contributing. 

First, can you give a bit of background about what the problem is, and how this PR solves it?

I see a comment about Gmail requiring SSL, but not much more. Are emails not being delivered to GMail addresses? Is it for local development only? I just tested the signup process at dmv and had no issues with a GMail account.

2019-07-16 04:05 UTC, KingMob commented
Sorry, @RubberRobot,  just caught up on the Discord conversation. I was going to suggest mailtrap.io as the best way forward, but then I saw you were having issues with it (maybe Mailosaur instead?). I  suspect mailtrap.io will *still* be easier, because I had nothing but hair-pulling trying to get my own dev environment to use GMail back in the day.

My only real concern is not adding complexity to the production mail setup, but other than that, this is fine with me.

2019-07-16 04:22 UTC, KingMob requested changes

2019-07-16 04:22 UTC, KingMob commented on src/clj/orcpub/email.clj
> +(def truthy? #{"true"})
If we're not going to use it anywhere else, it should probably not get a name and a var just yet. We can move the set `#{"true"}` to where `truthy?` is down below. Also, this doesn't match the current concept of truthy/falsy in Clojure, where falsy is `nil` or `false`, and truthy is anything else. It won't handle the inevitable user who uppercases it as "TRUE", either.

Alternatively, you could turn it into a fn that intelligently converts strings to booleans, and place it in a utility namespace. This is what the [cuerdas library's `to-bool`](https://funcool.github.io/cuerdas/latest/#to-bool) fn does. We could copy that or include cuerdas.

2019-07-16 20:01 UTC, KingMob commented
Anyone else want to comment?

2019-07-16 20:46 UTC, codeGlaze commented
I've been watching, most of my interaction happened in chat before the commit. Very happy this commit is happening. :)

2019-07-16 21:10 UTC, datdamnzotz commented
It looks good on paper. 👍 
I'd like to setup a mail server and test it with 25, 465, 587 just to make sure it works right under the covers.  I have the branch just haven't had time to test.

2019-07-17 14:43 UTC, KingMob submitted a review, later dismissed

2019-07-17 14:49 UTC, KingMob commented
I'm approving as far as I'm concerned, but I'd want to hear from Zotz on the server before merging. (Is there a way to go back to "unreviewed" after "request changes" in GitHub? I can only approve, or let my "request changes" continue to sit, even after my specific request is completed...)

2019-07-17 14:53 UTC, datdamnzotz commented
I'm testing this am.

2019-07-19 19:14 UTC, datdamnzotz approved these changes
Looks good 👍  Tested ok once I got the certs load correctly.

2019-07-19 19:14 UTC, merged