Fixed speed modifier type not displaying on the Item Builder
Orcpub/orcpub pull request #212
Opened 2019-07-23 10:16 UTC by RobinLefebvre

Easy fix that displays which of the Speed Bonus modifiers are associated with the form fields.

![Sans titre](https://user-images.githubusercontent.com/17627086/61704284-a9852480-ad43-11e9-930e-449b75e8fab3.png)

2019-07-27 01:31 UTC, KingMob requested changes
Apparently, there's already a `safe-capitalize-kw` fn that does this. I'd suggest switching to that.

2019-07-27 19:50 UTC, KingMob commented
`safe-capitalize-kw` invokes `(name)` for you, so you shouldn't call it yourself.

2019-07-27 19:53 UTC, KingMob requested changes
Remove unneeded `name` call

2019-07-27 20:58 UTC, datdamnzotz commented
> Remove unneeded `name` call

Omg. lol

2019-07-27 22:50 UTC, KingMob requested changes
Unfortunately, I just checked, and this doesn't work either. 

By removing `name`, but leaving the parentheses, you're now invoking `type-kw` as a function. (Keywords frequently act as functions, but that's not what we want here.)

You want to pass `type-kw` in, but not call it, so it should be `(common/safe-capitalize-kw type-kw)`.

2019-07-27 23:25 UTC, RobinLefebvre commented
As a note, I used `name` because it was missing, whereas other parts of the view were using it and worked as intended. If we are changing to `common/safe-capitalize-kw`, I can have the other parts of the view use it as well. Not sure *why* that matters however.

2019-07-28 01:33 UTC, KingMob commented
I definitely agree that having both fns lead to inconsistency in use. This is a large code base that was developed by just one person, so it has a lot of idiosyncrasies.

Honestly, if you want to combine the two into one fn and replace all usages in the code, I wouldn't object.

2019-07-28 01:34 UTC, KingMob commented
Let me know if you decide you don't want to mess with it further, and I'll approve.

2019-09-12 18:59 UTC, datdamnzotz commented
I think this is functional as is, we will just merge.

2019-09-12 18:59 UTC, merged