Fix orcpub mutiple rebuilds
Orcpub/orcpub pull request #30
Opened 2019-01-17 03:14 UTC by johnliss

2019-01-17 04:23 UTC, MeanderingCode commented
I'm curious what error this addresses?

Whenever I've built, the `ADD` is always run, so the `RUN lein uberjar` is always a new layer.

2019-01-17 14:37 UTC, johnliss commented
The behavior I was seeing was doing a 2nd or 3rd build wasn’t updating the pages with changes. The site contact email in the bottom left.  I ran the docker-compose up —build 3 times and there there was no changes.  I don’t think it was browser cache, chrome was in dev mode with cache disabled, and cloud flare was in dev mode as well.  I added the lien clean on my dev box and it worked. Then I pushed to dmv.com and it worked again.  Maybe I did something wrong but it seemed to fix the problem...

2019-01-18 18:42 UTC, MeanderingCode commented
This is odd behavior. I would like to do more testing, though in truth it should be negligible time addition to the build process, I just hate unnecessary code. Makes everything harder to understand, such as giving the impression that this is not a new filesystem for those who don't know Docker very well.

2019-01-18 20:09 UTC, johnliss commented
Yes it is odd  Perhaps nginx was caching? I'm not sure.  
lein clean then the build and changes showed up.

I've seen the same doing local builds as well.

2019-01-19 22:42 UTC, MeanderingCode commented
After further investigation, this turns out to be an nginx caching issue.

Possible reason is the server-wide `/etc/nginx/nginx.conf` file in the image having `sendfile on`, as there are some reports of errant behavior in VM and container environments.
Possible solutions:
* Turn `sendfile off`: undesired from performance perspective
* Turn 'gzip on`: Likely good solution, though implications should be thought through.

Interrim workaround: deploy new `web` container.

Open an issue on this if we want to do some testing on nginx configurations.

2019-01-19 22:44 UTC, MeanderingCode requested changes
After further investigation, this turns out to be an nginx caching issue.

Possible reason is the server-wide `/etc/nginx/nginx.conf` file in the image having sendfile on, as there are some reports of errant behavior in VM and container environments.
Possible solutions:

Turn `sendfile off`: undesired from performance perspective
Turn `gzip on`: Likely good solution, though implications should be thought through.
Interrim workaround: deploy new web container.

We can open an issue on this if we want to do some testing on nginx configurations, or you can simply do some experimentation with `gzip on`, comment here about any implications, revert your Dockerfile commit and add one with nginx conf changes.

2019-01-19 22:44 UTC, MeanderingCode commented on docker/orcpub/Dockerfile
> +	lein clean &&\
As per conversation, this is not necessary as the filesystem is fresh at this point.
More in review comment.

2019-01-20 22:05 UTC, johnliss commented
I'll defer to you guys.  It defiantly looked like a caching issue.

2019-01-21 21:42 UTC, Demonsthere reviewed
I agree with @MeanderingCode here, as we are working on a clean image, this shouln't be required

2019-01-23 07:13 UTC, johnliss commented
after testing it appears to be nginx cache. closed

2019-01-23 07:13 UTC, closed without merging