Implement roll buttons to be more compact
Orcpub/orcpub pull request #436
Opened 2020-07-30 19:28 UTC by Pireax

## Description:
Implements compact roll buttons, screenshots below of the new look:

![image](https://user-images.githubusercontent.com/11289656/88964572-ddc1e800-d2a9-11ea-83e8-8b8707f15c35.png)
![image](https://user-images.githubusercontent.com/11289656/88964592-e5818c80-d2a9-11ea-9791-b57f136dccb7.png)
![image](https://user-images.githubusercontent.com/11289656/88964604-ed413100-d2a9-11ea-944f-2a3148ae38be.png)
![image](https://user-images.githubusercontent.com/11289656/88965529-2f1ea700-d2ab-11ea-8d2a-16361956a832.png)
![image](https://user-images.githubusercontent.com/11289656/88965546-3645b500-d2ab-11ea-9f16-888cb962beab.png)

**Related issue (if applicable):** #427 

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [x] I have made corresponding changes to the documentation if necessary
  - [x] There is no commented out code in this PR.
  - [x] My changes generate no new warnings (check the console)

2020-08-20 15:15 UTC, datdamnzotz commented
@Pireax could you add the buttons to ability scores as well - something like:
![image](https://user-images.githubusercontent.com/3913859/90790792-aef5cb00-e2c5-11ea-8b39-36a6ee111ca6.png)
fair number of spells and contests that use raw modifiers

2020-08-22 16:51 UTC, Pireax commented
Good one, I'll take a look

2020-09-17 16:30 UTC, datdamnzotz requested changes
Waiting on Roll buttons

2020-09-29 17:42 UTC, datdamnzotz approved these changes

2020-09-29 20:51 UTC, merged