Fixes #508 wand of the war mage missing bonuses
Orcpub/orcpub pull request #512
Opened 2021-02-24 04:23 UTC by codeGlaze

## Description:

**Related issue (if applicable):** fixes #508
Wand of the War Mage was not applying the spell attack modifier.

**WARNING:  breaks existing name keys for the various Wands of the War Mage**

+ Introduce new generic function for creating items (focused on caster bonuses but could be generic)

+ Added some missing "action" blurbs

+ Fixes possible typo in `from-internal-item` properties

+ Automatic EOL changes to fit file format

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] I have commented my code, particularly in hard-to-understand areas
  - There **is** commented out code in this PR. Features to return to or tweak, primarily documentation related.
  - [x] My changes generate no new warnings (check the console)

2021-02-24 08:19 UTC, datdamnzotz requested changes
See inline comments

2021-02-24 08:19 UTC, datdamnzotz commented on src/cljc/orcpub/dnd/e5/magic_items.cljc
> +(defn
There already is a `spell-attack-modifier-bonus` and a `spell-save-dc-bonus` in modifiers.cljc
Do they not provide the functionality your after?

They can be used like this:
```
::modifiers [(mod5e/spell-attack-modifier-bonus 2)
(mod5e/spell-save-dc-bonus 3)]
```

2021-02-24 08:19 UTC, datdamnzotz commented on src/cljc/orcpub/dnd/e5/magic_items.cljc
> -     }{
I think you just need to add:

2021-02-24 08:19 UTC, datdamnzotz commented on src/cljc/orcpub/dnd/e5/magic_items.cljc
> -     ::attunement [:spellcaster]
```
::modifiers [(mod5e/spell-attack-modifier-bonus 1)
(mod5e/spell-save-dc-bonus 1)]
```

2021-02-24 08:19 UTC, datdamnzotz commented on src/cljc/orcpub/dnd/e5/magic_items.cljc
> -     ::attunement [:spellcaster]
```
::modifiers [(mod5e/spell-attack-modifier-bonus 2)
(mod5e/spell-save-dc-bonus 2)]
```

2021-02-24 08:19 UTC, datdamnzotz commented on src/cljc/orcpub/dnd/e5/magic_items.cljc
> -     ::attunement [:spellcaster]
```
::modifiers [(mod5e/spell-attack-modifier-bonus 3)
(mod5e/spell-save-dc-bonus 3)]
```

2021-02-24 08:19 UTC, datdamnzotz commented on src/cljc/orcpub/dnd/e5/magic_items.cljc
> +     }
and this whole section can be removed.

2021-02-24 12:56 UTC, codeGlaze commented
Did you read the actual function?

I used those modifiers, just abstracted it to cut down boilerplate code and potentially reuse for other items/custom items in the future.

2021-02-24 17:00 UTC, datdamnzotz commented
> That's exactly what I did.
> 
> I used those modifiers, just abstracted it to cut down boilerplate code and potentially reuse for other items/custom items in the future.

Looks like this is moving away from the convention that is already in place across all the magic items for three items.
This is really the data set for all magic items, they should follow the same syntax across all of them docha think?

I disagree with what he did with the `horn-of-valhalla` or `figurine-of-wondrous-power` if you search those items they are defined by a function.  There is a few of those.
They really should just be typed out like the rest instead of pushing functions for them.

I'm not apposed to introducing something like this - but imho it is the data set, probably should just follow that architecture - now if you want to update them all that's fine, but let's not just do 3.

2021-03-20 17:38 UTC, datdamnzotz commented
In https://dev.dungeonmastersvault.com for testing

2021-03-28 20:44 UTC, merged