Fixes 35 - PDF custom weapon display bug
Orcpub/orcpub pull request #605
Opened 2024-03-12 13:51 UTC by codeGlaze

## Description:

Subscribed the `all-weapons-map` to stay up to date via re-frame . . . bug squashed!

**Related issue:** fixes #35
## Checklist:
  - [x] The code change is tested and works locally.
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [x] I have made corresponding changes to the documentation if necessary
  - [x] There is no commented out code in this PR.
  - [x] My changes generate no new warnings (check the console)

2024-03-23 03:42 UTC, Jessomadic approved these changes

2024-03-23 03:42 UTC, Jessomadic approved these changes, later dismissed
Looks Good

2024-03-28 16:22 UTC, datdamnzotz requested changes
Pull the [rod-of-asclepius.svg](https://github.com/Orcpub/orcpub/pull/605/files#diff-943198d134836e5c1898247246de7af2cc4d10fd6ade9d0a55af486060944dec) from this commit and the other changes.

Other than that looks good

2024-03-28 16:25 UTC, datdamnzotz submitted a review, later dismissed

2024-03-28 16:26 UTC, datdamnzotz commented
n/m the image was already in there from a prior commit (missed that, thats on me)

2024-03-28 16:27 UTC, merged